# Generated by Django 4.1 on 2022-09-03 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phone', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='brand',
            table='brand',
        ),
        migrations.AlterModelTable(
            name='phone',
            table='phone',
        ),
        migrations.AlterModelTable(
            name='userphoneorder',
            table='user_phone_order',
        ),
        migrations.AlterModelTable(
            name='userphonereviews',
            table='user_phone_reviews',
        ),
    ]
