# Generated by Django 4.1 on 2022-09-03 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='mobile',
            field=models.CharField(default=None, max_length=10),
            preserve_default=False,
        ),
    ]
