# Generated by Django 4.1 on 2022-09-04 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_customuser_options_alter_customuser_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='mobile_number_verified',
            field=models.BooleanField(default=False),
        ),
    ]
